CREATE TABLE IF NOT EXISTS ratings
(
    id   SMALLINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS genres
(
    id   SMALLINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) UNIQUE NOT NULL,
    login    VARCHAR(255) UNIQUE NOT NULL,
    name     VARCHAR(255),
    birthday DATE                NOT NULL,
    CONSTRAINT chk_birthday CHECK (birthday <= CURRENT_DATE)
);

CREATE TABLE IF NOT EXISTS films
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(200),
    release_date DATE CHECK (release_date >= '1895-12-28'),
    duration     INTEGER CHECK (duration > 0),
    rating_id    SMALLINT,
    CONSTRAINT fk_rating FOREIGN KEY (rating_id) REFERENCES ratings (id) ON delete SET NULL
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  BIGINT   NOT NULL,
    genre_id SMALLINT NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    CONSTRAINT fk_film FOREIGN KEY (film_id) REFERENCES films (id) ON delete CASCADE,
    CONSTRAINT fk_genre FOREIGN KEY (genre_id) REFERENCES genres (id) ON delete CASCADE
);

CREATE TABLE IF NOT EXISTS likes
(
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, user_id),
    CONSTRAINT fk_like_film FOREIGN KEY (film_id) REFERENCES films (id) ON delete CASCADE,
    CONSTRAINT fk_like_user FOREIGN KEY (user_id) REFERENCES users (id) ON delete CASCADE
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id   BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (id) ON delete CASCADE,
    CONSTRAINT fk_friend FOREIGN KEY (friend_id) REFERENCES users (id) ON delete CASCADE,
    CONSTRAINT chk_not_self CHECK (user_id <> friend_id)
);